### ISSUE TITLE
training/labelmap.pbtxt; No such file or directory

### ISSUE THREAD

**Issue by ashoktcr** [Spidy20/face_mask_detection#1]
facemask-detection/models-master/research/object_detection/face_mask_detection-master/training/labelmap.pbtxt; No such file or directory

I cannot find labelmap.pbtxt in training folder after unzipping it.

**Comment by Spidy20** [comment]
It's alredy in zip, I given it, I told in installation you have to put all your files into object_detection folder, but I think you pasted whole folder in object_detection

**Comment by Spidy20** [comment]
Hey actually it's winrar issue, I will provide one drive link so from that you can download training folder
Because GitHub doesn't support more than 50 mb zip, but it's 550 mb
So I compressed it too much that's why it loose some files

**Comment by ashoktcr** [comment]
Thank you for quick reply. I got the files from your updated description .
