### ISSUE TITLE
ImportError: cannot import name 'string_int_label_map_pb2'

### ISSUE THREAD

**Issue by Nikhilbharadwaj08** [Spidy20/face_mask_detection#2]
ImportError: cannot import name 'string_int_label_map_pb2'

**Comment by Spidy20** [comment]
I already given regarding this solution on some GitHub forums, you will found search on google, I don't know solution currently

**Comment by Nikhilbharadwaj08** [comment]
> I already given regarding this solution on some GitHub forums, you will found search on google, I don't know solution currently
